"""add alert_events

Revision ID: 2ec6dd25e7de
Revises: 5afea87bfb56
Create Date: 2026-02-28 15:31:11.275172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec6dd25e7de'
down_revision: Union[str, Sequence[str], None] = '5afea87bfb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_assigned_user_id'), table_name='alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_assigned_user_id'), 'alerts', ['assigned_user_id'], unique=False)
    # ### end Alembic commands ###
