"""add assigned_user_id to alerts

Revision ID: 5afea87bfb56
Revises: 1441f56a86d9
Create Date: 2026-02-28 12:19:05.927956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5afea87bfb56'
down_revision: Union[str, Sequence[str], None] = '1441f56a86d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_v2_email'), table_name='users_v2')
    op.drop_index(op.f('ix_users_v2_id'), table_name='users_v2')
    op.drop_table('users_v2')
    op.alter_column('alerts', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('alerts', 'closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_alerts_assigned_user_id'), table_name='alerts')
    op.drop_constraint(op.f('alerts_assigned_user_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'users', ['assigned_user_id'], ['id'])
    op.alter_column('clients_v2', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('custom_lists', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sanctions', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sanctions', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('custom_lists', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients_v2', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_assigned_user_id_fkey'), 'alerts', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_alerts_assigned_user_id'), 'alerts', ['assigned_user_id'], unique=False)
    op.alter_column('alerts', 'closed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('alerts', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('users_v2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_v2_pkey'))
    )
    op.create_index(op.f('ix_users_v2_id'), 'users_v2', ['id'], unique=False)
    op.create_index(op.f('ix_users_v2_email'), 'users_v2', ['email'], unique=True)
    # ### end Alembic commands ###
